
tasks:
  - source: C:\Users\User\Documents\ploomber\environmnets\yafim-git-forked\ploomber\tests\assets/test-nb-inject-assets/template.ipynb
    name: task-a
    product: C:\Users\User\Documents\ploomber\environmnets\yafim-git-forked\ploomber\tests\assets/report-a.ipynb
    params:
      some_param: a

  - source: C:\Users\User\Documents\ploomber\environmnets\yafim-git-forked\ploomber\tests\assets/test-nb-inject-assets/template.ipynb
    name: task-b
    product: C:\Users\User\Documents\ploomber\environmnets\yafim-git-forked\ploomber\tests\assets/report-b.ipynb
    params:
      some_param: b
    