clients:
  # configures a dag-level File client
  File: clients.get_local # you can switch to clients.get_s3 or clients.get_gcloud

tasks:
  - source: functions.create_file
    # upon execution, this file is uploaded to storage
    product: products/some-file.txt
  
  - source: scripts/some-script.py
    # upon execution, both files are uploaded to storage
    product:
      nb: products/some-script.ipynb
      file: products/another-file.txt
    # you may also pass a task-level File client if you don't want to upload
    # all products in the pipeline
    # client: clients.get_s3